# Generated by Django 4.2.4 on 2023-09-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('no_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='time duration for this quiz')),
                ('required_score_to_pass', models.IntegerField(help_text='min score required for this quiz')),
                ('diffculty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6)),
            ],
        ),
    ]
